
services:
  router1:
    build:
      context: .
    container_name: router1
    networks:
      net_wan:
        ipv4_address: 10.0.0.2
      net_lan:
        ipv4_address: 172.16.0.2
      net_bgp:
        ipv4_address: 192.168.10.2
    ports:
      - "2221:22"  # Puerto SSH
    volumes:
      - ./quagga_rt1.config:/etc/quagga/bgpd.conf

  router2:
    build:
      context: .
    container_name: router2
    networks:
      net_wan:
        ipv4_address: 10.0.0.3
      net_lan:
        ipv4_address: 172.16.0.3
      net_bgp:
        ipv4_address: 192.168.10.3
    ports:
      - "2222:22"  # Puerto SSH
    volumes:
      - ./quagga_rt2.config:/etc/quagga/bgpd.conf

  router3:
    build:
      context: .
    container_name: router3
    networks:
      net_wan:
        ipv4_address: 10.0.0.4
      net_lan:
        ipv4_address: 172.16.0.4
      net_bgp:
        ipv4_address: 192.168.10.4
    ports:
      - "2223:22"  # Puerto SSH
    volumes:
      - ./quagga_rt3.config:/etc/quagga/bgpd.conf

  router4:
    build:
      context: .
    container_name: router4
    networks:
      net_wan:
        ipv4_address: 10.0.0.5
      net_lan:
        ipv4_address: 172.16.0.5
      net_bgp:
        ipv4_address: 192.168.10.5
    ports:
      - "2224:22"  # Puerto SSH
    volumes:
      - ./quagga_rt4.config:/etc/quagga/bgpd.conf

networks:
  net_wan:
    name: docker_rt1_rt2_wan
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
  net_lan:
    name: docker_rt1_rt2_lan
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
  net_bgp:
    name: docker_rt1_rt2_bgp
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
