version: '3.8'

services:
  router1:
    image: docker_rt1_rt2-router1
    container_name: router1
    networks:
      netdevops_bridge:
        ipv4_address: 192.168.1.2

  router2:
    image: docker_rt1_rt2-router2
    container_name: router2
    networks:
      netdevops_bridge:
        ipv4_address: 192.168.1.3

networks:
  netdevops_bridge:
    name: docker_rt1_rt2_netdevops_bridge  # Asegúrate de que coincide con el nombre de la red inspeccionada
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
